/**
 * The public API of `@lore/okf` as text: every export of `src/index.ts` with its signature.
 * Plans 2 and 3 code against this surface, so it is frozen (plans/01-okf-vault-toolkit.md,
 * section 3). A change to it has to be deliberate: bump the version, describe the change in
 * CHANGELOG.md, then record the new surface.
 *
 *   pnpm --filter @lore/okf api:update
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const API_FILE = join(PKG, "api/okf.api.txt");
export const CHANGELOG_FILE = join(PKG, "CHANGELOG.md");

export function packageVersion(): string {
  return (JSON.parse(readFileSync(join(PKG, "package.json"), "utf8")) as { version: string })
    .version;
}

/** One line per export, sorted by name, so the file diffs cleanly. */
export function describeApi(): string {
  const entry = join(PKG, "src/index.ts");
  const config = ts.readConfigFile(join(PKG, "tsconfig.json"), ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, PKG);
  const program = ts.createProgram([entry], { ...parsed.options, noEmit: true });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(entry);
  const moduleSymbol = source && checker.getSymbolAtLocation(source);
  if (!moduleSymbol) throw new Error(`Cannot read ${entry}`);

  const flags =
    ts.TypeFormatFlags.NoTruncation |
    ts.TypeFormatFlags.UseFullyQualifiedType |
    ts.TypeFormatFlags.WriteArrowStyleSignature;
  const lines: string[] = [];
  for (const exported of checker.getExportsOfModule(moduleSymbol)) {
    const symbol =
      exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported;
    const decl = symbol.declarations?.[0];
    if (!decl) continue;
    const name = exported.getName();
    let kind: string;
    let shape: string;
    if (ts.isInterfaceDeclaration(decl) || ts.isTypeAliasDeclaration(decl)) {
      kind = ts.isInterfaceDeclaration(decl) ? "interface" : "type";
      const type = checker.getDeclaredTypeOfSymbol(symbol);
      const props = checker.getPropertiesOfType(type);
      shape =
        ts.isInterfaceDeclaration(decl) && props.length
          ? "{ " +
            props
              .map((p) => {
                const optional = p.flags & ts.SymbolFlags.Optional ? "?" : "";
                const t = checker.typeToString(
                  checker.getTypeOfSymbolAtLocation(p, decl),
                  decl,
                  flags,
                );
                return `${p.getName()}${optional}: ${t}`;
              })
              .join("; ") +
            " }"
          : checker.typeToString(type, decl, flags | ts.TypeFormatFlags.InTypeAlias);
    } else if (ts.isClassDeclaration(decl)) {
      kind = "class";
      const instance = checker.getDeclaredTypeOfSymbol(symbol);
      const ctor = checker
        .getTypeOfSymbolAtLocation(symbol, decl)
        .getConstructSignatures()
        .map((s) => checker.signatureToString(s, decl, flags))
        .join(" | ");
      const members = checker
        .getPropertiesOfType(instance)
        .filter((p) => {
          const d = p.declarations?.[0];
          const mods = d && ts.canHaveModifiers(d) ? ts.getModifiers(d) : undefined;
          return !mods?.some((m) => m.kind === ts.SyntaxKind.PrivateKeyword);
        })
        .map(
          (p) =>
            `${p.getName()}: ${checker.typeToString(checker.getTypeOfSymbolAtLocation(p, decl), decl, flags)}`,
        );
      shape = `new ${ctor} { ${members.join("; ")} }`;
    } else {
      kind = ts.isFunctionDeclaration(decl) ? "function" : "const";
      shape = checker.typeToString(checker.getTypeOfSymbolAtLocation(symbol, decl), decl, flags);
    }
    lines.push(`${kind} ${name}: ${shape.replace(/\s+/g, " ")}`);
  }
  lines.sort((a, b) => {
    const x = a.slice(a.indexOf(" ") + 1);
    const y = b.slice(b.indexOf(" ") + 1);
    return x < y ? -1 : x > y ? 1 : 0;
  });
  return lines.join("\n") + "\n";
}

export function header(version: string): string {
  return `# Public API of @lore/okf ${version}. Generated by scripts/api.ts; do not edit.\n`;
}

export function recordedVersion(text: string): string | null {
  return /^# Public API of @lore\/okf (\S+)\./.exec(text)?.[1] ?? null;
}

export function changelogHas(version: string): boolean {
  const text = readFileSync(CHANGELOG_FILE, "utf8");
  return new RegExp(`^## ${version.replace(/\./g, "\\.")}( |$)`, "m").test(text);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const version = packageVersion();
  const api = describeApi();
  let previous = "";
  try {
    previous = readFileSync(API_FILE, "utf8");
  } catch {
    // first run
  }
  const body = previous.slice(previous.indexOf("\n") + 1);
  if (previous && body !== api && recordedVersion(previous) === version) {
    console.error(
      `The public API changed but the version is still ${version}.\n` +
        "Bump the version in packages/okf/package.json, describe the change in CHANGELOG.md, and run this again.",
    );
    process.exit(1);
  }
  if (!changelogHas(version)) {
    console.error(`CHANGELOG.md has no "## ${version}" section.`);
    process.exit(1);
  }
  writeFileSync(API_FILE, header(version) + api);
  console.log(`Recorded the API of @lore/okf ${version}: ${api.split("\n").length - 1} exports`);
}
